# SPDX-License-Identifier: MIT
# Solar Meshtastic Node (Heltec HT-CT62, ESP32-C3) + SX1262

CONFIG_ZEPHCORE_BOARD_NAME="Solar Meshtastic Node"
CONFIG_BT_DIS_MODEL_NUMBER_STR="Solar Meshtastic Node"

# CONFIG_ZEPHCORE_ADMIN_PASSWORD="password"

# EU868/Narrow preset (869.618 MHz / 62.5 kHz / SF 8)
CONFIG_ZEPHCORE_DEFAULT_LORA_SF=8

CONFIG_ZEPHCORE_LORA_RX_DUTY_CYCLE=y

CONFIG_ZEPHCORE_MAX_CONTACTS=300
